Return message in case of package-lock.json needs regeneration.

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -794,6 +794,13 @@ jobs:
       run: |
         cd ffi/diplomat/wasm
         npm ci
+        if $?
+        then
+          echo Execution of 'npm ci' failed. This may be due to package.json
+          echo and package-lock,json being out of sync. Locally execute
+          echo 'npm install' in directory  ffi/diplomat/wasm to generate a
+          echo new package-lock.json file and and merge it into the repository.
+          exit 1
 
     - name: Set path to wasm-opt and wabt binaries
       run: |
